### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by ChessWaveIO** [espressoVi/ChessVisionChallenge#1]
Background textures for `board.blend` are missing from the repository.

**Comment by espressoVi** [comment]
All the auxiliary data was too big for github, I have uploaded them to google drive. [Here is the link](https://drive.google.com/file/d/1DEeD4MJslyM9U71pNHdRnUVhO-CRwrwJ/view?usp=drive_link). I hope this tarball (~500MB inflating to ~1.4GB) solves the issue.

**Comment by ChessWaveIO** [comment]
Thanks. I suggest packing the data then updating the blend file. Here is an [example](https://blender.stackexchange.com/questions/39257/packing-texture-files-in-a-single-blend-filel)

**Comment by espressoVi** [comment]
Thank you for the helpful suggestion. I have done so in the latest commit, please let me know if it works.

**Comment by ChessWaveIO** [comment]
Yes that worked. Thanks!
